# docker-compose.yml

version: '3'
services:
  web:
    build:
      context: ./src
      dockerfile: ../Dockerfile
    ports:
    - 3000:3000
    volumes:
      - ./src:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql://root@mysql:3306/rna
    depends_on:
      - mysql

  mysql:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      DATABASE: rna

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 64M

volumes:
  db-data: